import { StatusBar } from 'react-native'

const STATUSBAR_HEIGHT = StatusBar.currentHeight
const MIN_HEADER_HEIGHT = 60 
const NAVBAR_HEIGHT = 50
const MAX_HEADER_HEIGHT = STATUSBAR_HEIGHT + MIN_HEADER_HEIGHT
const MEDIUM_HEADER_HEIGHT = STATUSBAR_HEIGHT + NAVBAR_HEIGHT 
const TOTAL_HEADER_HEIGHT = STATUSBAR_HEIGHT + MIN_HEADER_HEIGHT + NAVBAR_HEIGHT

const DIMENSION = {
  STATUSBAR_HEIGHT: STATUSBAR_HEIGHT,
  MIN_HEADER_HEIGHT: MIN_HEADER_HEIGHT,
  NAVBAR_HEIGHT: NAVBAR_HEIGHT,
  MAX_HEADER_HEIGHT: MAX_HEADER_HEIGHT,
  MEDIUM_HEADER_HEIGHT: MEDIUM_HEADER_HEIGHT,
  TOTAL_HEADER_HEIGHT: TOTAL_HEADER_HEIGHT,
}

export default DIMENSION