import { StatusBar } from 'react-native'

const STATUSBAR_HEIGHT = StatusBar.currentHeight
const MIN_HEADER_HEIGHT = 60 
const MAX_HEADER_HEIGHT = STATUSBAR_HEIGHT + MIN_HEADER_HEIGHT
const NAVBAR_HEIGHT = 50
const TOTAL_HEADER_HEIGHT = STATUSBAR_HEIGHT + MIN_HEADER_HEIGHT + NAVBAR_HEIGHT

/* const DIMENSION = {
  STATUSBAR_HEIGHT: STATUSBAR_HEIGHT,
  MIN_HEADER_HEIGHT: MIN_HEADER_HEIGHT,
  MAX_HEADER_HEIGHT: MAX_HEADER_HEIGHT,
  NAVBAR_HEIGHT: NAVBAR_HEIGHT,
  TOTAL_HEADER_HEIGHT: TOTAL_HEADER_HEIGHT
} */

const DIMENSION = {
  STATUSBAR_HEIGHT: StatusBar.currentHeight,
  MIN_HEADER_HEIGHT: 60,
  MAX_HEADER_HEIGHT: StatusBar.currentHeight + 60,
  NAVBAR_HEIGHT: 50,
  TOTAL_HEADER_HEIGHT: '60'
}

export default DIMENSION
