const SearchViewerListDataTest = [
  {
    id: "0",
    nom: "pakgne group",
    type: "group",
    img: "../assets/default_100.jpg",
    last_comment: "Dernier commentaire",
  },
  {
    id: "1",
    nom: "happy",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "2",
    nom: "jaz.b",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "3",
    nom: "e.y.o",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "4",
    nom: "gabin",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "5",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "6",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "7",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "8",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "9",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "10",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "11",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "12",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "13",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "14",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "15",
    nom: "user",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
]

export default SearchViewerListDataTest

