const DATATEST = [
  {
    id: "0",
    nom: "Pakgne Group",
    type: "group",
    img: "../../../assets/default_100.jpg",
    last_comment: "Dernier commentaire",
  },
  {
    id: "1",
    nom: "Happy",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "2",
    nom: "JAZ.B",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "3",
    nom: "E.Y.O",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "4",
    nom: "Gabin",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "5",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "6",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "7",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "8",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "9",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "10",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "11",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "12",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "13",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "14",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
  {
    id: "15",
    nom: "User",
    type: "user",
    img: "",
    last_comment: "Dernier commentaire",
  },
]

export default DATATEST

